name: Release

on:
  push:
    branches:
      - main

env: 
  node_version: 22

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://npm.pkg.github.com'
      
      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm i

      - name: Check for changesets
        run: pnpm run ci:hasChanges

      - name: Build
        run: pnpm build

      - name: Publish to GitHub Packages
        run: pnpm publish

      - name: Create git Tag
        run: pnpm run ci:git:tag

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     # This expects you to have a script called release which does a build for your packages and calls changeset publish
      #     publish: pnpm ci:publish
      #     commit: "chore(release): changesets versioning & publication"
      #     title: "Changesets: Versioning & Publication"
      #     createGithubReleases: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
